<a href="https://colab.research.google.com/github/baiqtiara/baiqtiara/blob/main/Latihan_pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
#slide 6 Buatlah list dengan nama "Mahasiswa" yang berisi Nama, NIM, Prodi, Mata Kuliah, Tanggal hari ini, nama Universitas

import datetime
Mahasiswa = ["Tiara", 2022071079, "Informatika", "Desain and analisis algoritma", datetime.date.today(), "Universitas pembangunan jaya"]
print(Mahasiswa)


['Tiara', 2022071079, 'Informatika', 'Desain and analisis algoritma', datetime.date(2023, 9, 16), 'Universitas pembangunan jaya']


In [40]:
#slide 8 Cetak NIM masing-masing dengan memanggil urutan indeks dalam list "Mahasiswa"!

Mahasiswa=["Tiara", 2022071079, "informatika", "Desain and analisis algoritma", datetime.datetime.now(), "Universitas Pembangunan Jaya"]
Mahasiswa[1:2]

[2022071079]

In [45]:
#slide 9

Mahasiswa=["Tiara", 2022071079, "informatika", "Desain and analisis algoritma", datetime.datetime.now(), "Universitas Pembangunan Jaya"]
Mahasiswa[5:6]


['Universitas Pembangunan Jaya']

In [46]:
#slide 11 Cetak NIM dan Prodi menggunakan slicing!

Mahasiswa=["Tiara", 2022071079, "informatika", "Desain and analisis algoritma", datetime.datetime.now(), "Universitas Pembangunan Jaya"]
Mahasiswa[1:2]


[2022071079]

[2022071079]

In [47]:
#slide 11 Cetak NIM dan Prodi menggunakan slicing!

Mahasiswa=["Tiara", 2022071079, "informatika", "Desain and analisis algoritma", datetime.datetime.now(), "Universitas Pembangunan Jaya"]
Mahasiswa[2:3]


['informatika']

In [48]:
#slide 13 Cetak isi list "Mahasiswa" tambahkan kata "UPJ" di depan!

Mahasiswa=["Tiara", "Informartika", "Desain and analisis algoritma", "Universitas Pembangunan Jaya"]
for aMahasiswa in Mahasiswa:
  print("Universitas Pembangunan Jaya " + aMahasiswa)


Universitas Pembangunan Jaya Tiara
Universitas Pembangunan Jaya Informartika
Universitas Pembangunan Jaya Desain and analisis algoritma
Universitas Pembangunan Jaya Universitas Pembangunan Jaya


In [49]:
#slide 15 Susun Tuple bernama "UPJ", isi dengan Universitas, Pembangunan, Jaya

UPJ=('Universitas', 'Pembangunan', 'Jaya')
UPJ[1:2]


('Pembangunan',)

In [50]:
#slide 17 Buat Tuple bersarang bernama "nested_tuple" dengan nilai : pertama=100 kedua=200,400,600 ketiga=300 keempat=400,800

Nested_tuple = ("pertama","kedua","ketiga","keempat")
Nested_nilai = ("100","200,400,600","300", "400,800")

print(Nested_tuple, Nested_nilai)

('pertama', 'kedua', 'ketiga', 'keempat') ('100', '200,400,600', '300', '400,800')


In [51]:
#slide 21

Mahasiswa={"Nama": "BaiqTiara" , "NIM": "2022071079" , "Prodi": "informatika" ,  "Universitas": "UPJ"}
print(Mahasiswa)


{'Nama': 'BaiqTiara', 'NIM': '2022071079', 'Prodi': 'informatika', 'Universitas': 'UPJ'}


In [52]:
#slide 34

#>>>yellow|red {'dandelions','fire hydrant','blood','rose','leaves'}
#>>>yellow&red {'leaves','firehydrant'}
yellow = {'dandelions','fire hydrant','leaves'}
red = {'leaves', 'fire hydrant','rose','blood'}
print(yellow|red)
print(yellow&red)

{'rose', 'blood', 'leaves', 'fire hydrant', 'dandelions'}
{'leaves', 'fire hydrant'}


In [53]:
#slide 41

data={
    "no":[1,2,3],
    "prodi": ["informatika","Sistem informasi","Teknik Sipil"],
    "Mahasiswa": [50 ,55 ,40],
    "lakilaki": [30,30,30],
    "Perempuan" : [20,25,10]
}
df = ("data, index = ['-','-','-']")
print(df)

data, index = ['-','-','-']


In [54]:
#slide 44 Buatlah matrix & transpose matriks
import numpy as np
matriksA = np.array ([[100,200,300],
                      [700,600,500],
                      [900,1000,800]])

print("matriks A:")
print(matriksA)

transpose_matriks = np.transpose(matriksA)

print("Transpose Matriks A:")
print(transpose_matriks)

matriks A:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transpose Matriks A:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
